apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
      - name: order
        image: peternedergaard/pejomi-order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083